### ISSUE TITLE
Modify uboot resolution

### ISSUE THREAD

**Issue by sintian** [TechNexion-customization/ubuntu-tn-imx#13]
My platform is i.MX6DL and 7" monitor (with LVDS interface).
After modifying the dtb, the display in the kernel is very good, but the boot image of uboot is still at the original resolution (1024*600). I want to adjust it to a resolution of 800x480. Where can I modify it?
Thanks!

**Comment by richard-hu** [comment]
Hi, @sintian 

Sorry for the late reply.

It would not take much effort to enable LVDS in u-boot since you have working display timing in linux kernel. 

There is an example to add new LVDS panel support in u-boot. Please refer to the commit below:
https://github.com/TechNexion/u-boot-edm/commit/92d7b91fb324e32914e589dee67b8203d223166b

BR,

Richard

**Comment by sintian** [comment]
hi @richard-hu 
It works! Thank you so much!
Best regards.

**Comment by richard-hu** [comment]
Great~!!!
