### ISSUE TITLE
Build image failed with edm-g-imx8mp

### ISSUE THREAD

**Issue by LeoChang88** [TechNexion-customization/ubuntu-tn-imx#9]
Hi,

Some error occurred when I try to build Ubuntu 20.04 image for EDM-G-IMX8M-PLUS,
please help to check the error log .
My host system is Ubuntu 20.04.
Thank you.

[build_image.txt](https://github.com/TechNexion-customization/ubuntu-tn-imx/files/7235092/build_image.txt)

**Comment by wigcheng** [comment]
Missing u-boot and kernel image, please issue command to compile first:
make **all** PLATFORM="edm-g-imx8mp"

**Comment by LeoChang88** [comment]
Hi,
Thanks for your reply,
actually I tried this command (make all PLATFORM="edm-g-imx8mp") first and it shows the same error log,
so I try to make partial build for debugging, and u-boot building seems OK.
[build_u-boot.txt](https://github.com/TechNexion-customization/ubuntu-tn-imx/files/7235387/build_u-boot.txt)

**Comment by wigcheng** [comment]
No, it seems your flash.bin cannot generate correctly according your u-boot log.
Do you use virtual machine, or host PC?

You can try to compile flash.bin manually as follows steps:
1. cd output/u-boot/u-boot-tn-imx
2. ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- ./install_uboot_imx8.sh -b imx8mp-edm-g.dtb -d /dev/null

And provide me the results, thanks.

**Comment by LeoChang88** [comment]
Hi,
I'm using virtual machine.
that's the result:
[u-boot_log.txt](https://github.com/TechNexion-customization/ubuntu-tn-imx/files/7240575/u-boot_log.txt)

**Comment by wigcheng** [comment]
I have a question: Is the root permission is necessary by your side?
After I saw the log, it's due to you adapt 'sudo' permission to generate ubuntu image, and u-boot default setting does not support it.

If you can make images without sudo, I think it should be works, or you have to modify install_uboot_imx8.sh script manually (comment from line 303 to line 307 to enable root supporting), but it's dangerous behavior, could be damage your system if you assign wrong device node.

Thanks.

**Comment by LeoChang88** [comment]
Hi,
Thanks for your reply, you are right, it works without "sudo".
I have another question about the audio jeck "AUDIO1", it doesn't  make a sound when I play wav file by"aplay test.wav".

Thank you.

**Comment by wigcheng** [comment]
Please create another ticket if you have other questions, and close this issue.

I can answer your this time, only this time! If your aplay works without sound, it always due to no assign specific audio interface, assuming you want to output audio jack, you need issue command such as:
$ aplay -Dhw:1 test.wav

Default is output to hw:0 interface, and it's hdmi audio.

**Comment by LeoChang88** [comment]
Hi,
It works, I'll close this issue,
thank you.
